### ISSUE TITLE
Empty subscription in class removes other classes as well.

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/brisky-class#2]
```
icon: {
  class: {
    icon: true
  }
}
```

```
logo: {
  type: { 'icon' },
  class: { 
    disabled: {  
      $: 'blaa'
    }
  }
}
```

if `blaa` is empty, it removes icon class from constructor as well.

**Comment by nikoloza** [comment]
@youzi - Real example (it's not icon, it's row - icon was for example only, don't get confused):
https://github.com/vigour-io/play-modal/blob/4ea3e29d103d37a5b3f46e2b7eb60b848223233f/lib/types/row/index.js#L77
https://github.com/vigour-io/play-modal/blob/cf9a28334b7d1998b45466346fad7ef7c90b9c10/lib/tpay/step1.js#L54

**Comment by jimdebeer** [comment]
@nikoloza did you try it on the newest stuff?

**Comment by jimdebeer** [comment]
(state v 4, brisky-core 1.4) ?

**Comment by jimdebeer** [comment]
check this test https://github.com/vigour-io/brisky-class/blob/master/test/context.js#L91
@nikoloza can you try to add your breaking case in a test here? can't recreate

**Comment by nikoloza** [comment]
In tests the same thing works.
But here it does not: https://github.com/vigour-io/play-modal/blob/master/lib/index.js#L8-L21
I'm trying to find out what does this cause.

**Comment by jimdebeer** [comment]
so you could not recreate it in tests? -- try multiple types maybe -- make it like a page -- start with a lot then break it down #artofdebug

**Comment by nikoloza** [comment]
Yes, I'm trying to see it more in isolation, only in play-modal.

**Comment by jimdebeer** [comment]
play modal was a different issue (see the code in play-modal that does all kinds of custom class things)
